version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs: 
  test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}-<< parameters.node-version >>
          paths:
            - node_modules
      - run:
          name: Run test using nodejs << parameters.node-version >>
          command: node test.js

workflows:
  all-test:
    jobs:
      - test: 
          matrix:
            parameters:
              node-version: ['lts', 'current']