version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:lts
    resource_class: large
    parallelism: 10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Run test using nodejs
          command: node test.js

workflows:
  build_and_test:
    jobs:
      - build